### ISSUE TITLE
Add a way to disable the event

### ISSUE THREAD

**Issue by D3add3d** [kidh0/jquery.idle#12]
Please add someting like $(document).off('idle') to disable/remove the idle timer

**Comment by zachdixon** [comment]
I would definitely like to use this, but would also definitely need some way to accomplish this. Maybe something like `$(document).idle('stop')` that would call `$(document).off('mousemove.idle')` etc. for each of the configured events.

**Comment by kidh0** [comment]
@D3add3d and @zachdixon, take a look in the version 1.2.3 (367ea505a9aace04f5dd7952cea7671ae3e3ca70). I just add this request.

**Comment by zachdixon** [comment]
very nice! thanks @kidh0
