### ISSUE TITLE
 startAtIdle option doesnot work as expected.

### ISSUE THREAD

**Issue by KKirad** [kidh0/jquery.idle#15]
handleIdleCondition: function(){
      $(document).idle({
        onIdle: function() {
          console.log("Idle");
        },
        idle: 60000,
        startAtIdle: true
      });
    }

If the page is kept idle for 60000ms i.e 1min it prints 'Idle'. But if the page is kept idle for 2min it should display 'Idle' twice as startAtIdle option is set to true. Please Correct me if i'm wrong.

**Comment by kidh0** [comment]
Could you please create a jsfiddle for this issue ?

**Comment by KKirad** [comment]
This issue has been resolved in version 1.2.5. Thanks.
