### ISSUE TITLE
Not working on iframes

### ISSUE THREAD

**Issue by PaoloFalomo** [kidh0/jquery.idle#19]
Hi! This plugin is cool but not works with cross-origin iframes. 

[JSFIDDLE HERE](https://jsfiddle.net/xpol555/771r19r3/1/)

**Comment by mubasherusman** [comment]
How to use "idle:stop" when we I allredy has idle:10000 registered. 
`$(document).idle({
      onIdle: function(){
        $('#status').toggleClass('idle').html('Idle!');
      },idle: 2000,
      keepTracking: true
    });`

**Comment by kidh0** [comment]
Yes, this is a known issue. I recommend in this case (youtube video), to use the Youtube JS API, it will be much more easier.
