### ISSUE TITLE
Reset idle when a video is playing

### ISSUE THREAD

**Issue by moisesnandres** [kidh0/jquery.idle#21]
I want to reset the idle time when a video is playing (I'm using the element <video>)
So I add to the events the next:
`events: 'mousemove keydown mousedown touchstart progress play playing'`
But it's not working with the video.
What event do I have to use?

**Comment by moisesnandres** [comment]
Nvm, I solved my problem.
Thanks for the plugin :+1:

**Comment by marianoarga** [comment]
@moisesnandres could you share your solution?

**Comment by moisesnandres** [comment]
Hi @marianoarga , my first solution was use
`$(document).trigger('idle:stop');`
After the video start playing but I also need to call the idle function when it had spent 1 minute.
So, my second solution was
```
sliderItem.find(findVideo).trigger('play').show();
const videoDuration = sliderItem.find(findVideo).attr('duration');
idleDuration = (videoDuration * 1000) + 60000;
$(document).trigger('idle:stop');
setIdle();
```
My setIdle function is 
```
function setIdle() {
  $(document).idle({
    onIdle() {
      $('.intro').show().removeClass('zoomOut').addClass('zoomIn');
      setTimeout(() => {
        reset();
        $('.intro').removeClass('zoomIn');
      }, 1000);
    },
    idle: idleDuration,
  });
}
```
