### ISSUE TITLE
onHide being fired on load

### ISSUE THREAD

**Issue by kissit** [kidh0/jquery.idle#23]
Hi There,

First thank you for this plugin.  The simplicity is nice.  I'm seeing the onHide event being fired immediately following page load even though the window is still active, in addition to the correct behavior when the page is in fact hidden/tab changed/etc.  I believe my usage is correct (see below), maybe a bug?

Any help is greatly appreciated.

```
$(document).idle({
        idle: 10000,
        onIdle: function(){
            console.log('onIdle called');
        },
        onActive: function(){
            console.log('onActive called');
        },
        onHide: function(){
            console.log('onHide called');
        },
        onShow: function(){
            console.log('onShow called');
        }
    });
```

**Comment by kidh0** [comment]
Could you please create a jsfiddle reproducing the bug?

**Comment by kissit** [comment]
Sorry, I'm honestly not sure as I ended up having to go a different direction anyway.  So as far as I'm concerned no, this can be closed.  Thanks!
