### ISSUE TITLE
Ignore while html5 video playing

### ISSUE THREAD

**Issue by jaluka** [kidh0/jquery.idle#26]
Hi,

I was wondering how to use this with html5 videos, in that while a video is playing I don't want it to timeout, but if the video is paused/stopped/finished then the timeout can occur.

**Comment by kidh0** [comment]
I think that you could create a status variable for the video playback and while it is being played reset the idle using the idle:stop event. Maybe I can help you more if you share some example of what you are trying to achieve.

**Comment by kidh0** [comment]
Is this still a problem?

**Comment by uhYeah** [comment]
Hi Henrique,

same problem here.
I'm using playr which provides Media Events to check the states. But I couldn't figure out how to use your stop event. Would be cool, if you could show an example.

The Media Events in playr are working like this:
```
player.on('playing', event => {
    console.log('stop idle');
});
player.on('pause', event => {
    console.log('resume idle');
});
```
Thank you.

**Comment by kidh0** [comment]
@uhYeah seems that you are calling the plugin with a wrong **idle** value. Try using this instead:

`$(document).idle({
  onIdle: function(){
    alert('Bla Bla Bla');
  },
  idle: 1000
})`

Take a look at the docs https://github.com/kidh0/jquery.idle#usage, I guess that will be easier to understand ;)

**Comment by uhYeah** [comment]
Oh, I get it all wrong.
And now I saw that the problem was solved in an other Issue before.
Sorry for the confusion and thanks for your help.
