### ISSUE TITLE
onHide for a specific time!

### ISSUE THREAD

**Issue by adhip94** [kidh0/jquery.idle#28]
Currently from what I have read on the github page, if I change a tab or minimize the browser window it will immediately trigger the onHide method! Is it possible to trigger the onHide method after a specific amount of time like the idle function, for example if the user has changed the tab and I want to display an alert like 15 seconds after the tab was switched?

**Comment by kivervinicius** [comment]
setTimeout can help you, or no?

**Comment by kivervinicius** [comment]
onShow you trigger clearTimeout if setTimeout don't trigger

**Comment by kidh0** [comment]
I think that this is no longer a problem, so I will close the issue.
