### ISSUE TITLE
Write better explanation how to use "idle:stop"

### ISSUE THREAD

**Issue by gentle-media** [kidh0/jquery.idle#35]
Could you please explain better how to use "idle:stop". I have an AJAX site where I have an audio player, so I want to stop idle() if the user clicks on 'play'.

I tried the following, but no luck.

```
$(document).idle({
    onIdle: function(){
        window.location.reload();
    },
    idle: 10000
})


$('.play').on('click', function() {
    $(document).idle({
        idle: stop // does not work
        idle: 'stop' // does not work too
        idle: 'idle:stop' // does not work either
    })
});
```

**Comment by kidh0** [comment]
Hi, you could use the jQuery `trigger` method to _trigger_ the `idle:stop`, just like that:
```js
$(document).trigger('idle:stop');
```
Give it a try and let me know if it works.

**Comment by gentle-media** [comment]
Thanks @kidh0 ... I should have indeed used the `trigger()` method. All good now! :)
